### ISSUE TITLE
Create a users list

### ISSUE THREAD

**Issue by KevinTss** [fitigai/admin#23]
# Context

Based on #1 you should now have a users page. Add it a table by fetching data from a fake API for now ([JSONPlaceholder](https://jsonplaceholder.typicode.com/)) in order to list all users.

# Todo's

- [ ] Create the table UI elements
- [ ] Fetch users
- [ ] Display a spinner (loader UI element) when data are fetching
- [ ] For each row of the table, we should have an action button how allow us to make actions (See full profile, Delete)

## Table example

| Created At | Full name | Email | Phone | Actions |
|---|---|---|---|---|
| June 01, 2021 | John Doe | john.doe@email.com | +32 (0)476 78 91 23 | [BUTTON] |
| ... | ... | ... | ... | ... |
